version: '3'

services:
  nginx_vpn:
    image: nginx:latest
    container_name: nginx_vpn
    network_mode: "host"
    volumes:
      - ./nginx_vpn.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_configs/vpn:/etc/nginx/conf.d:ro
    extra_hosts:
      - "portainer.rem:10.0.0.2"
    networks:
      - infra

    nginx_public:
      image: nginx:latest
      container_name: nginx_loadbalancer
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx_public.conf:ro
        - ./nginx_configs/public:/etc/nginx/conf.d:ro
      networks:
        - infra

  nginx_http:
    image: nginx:latest
    container_name: nginx_http_server
    ports:
      - "8080:80"  # Exposing the HTTP server on port 8080
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro  # Serve static files from ./html
      - ./gear.svg:/usr/share/nginx/gear.svg:ro
    networks:
      - infra

  smtp:
    image: mailhog/mailhog
    container_name: smtp_server
    ports:
      - "1025:1025"  # SMTP Server
      - "8025:8025"  # Web UI (optional)
    networks:
      - infra

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - infra

volumes:
  portainer_data:

networks:
  infra:
    driver: bridge